### ISSUE TITLE
Document how to write a program that talks to this?

### ISSUE THREAD

**Issue by glasser** [keyboardio/Kaleidoscope-Focus#7]
The readme is super clear on how to write the keyboard driver half of a Focus plugin, but it would be awesome to have some description or links to an example of how a program running on your computer that talks to it works.

**Comment by algernon** [comment]
There's a [small tool](https://github.com/keyboardio/Kaleidoscope-Focus/blob/master/extras/kaleidoscope-focus.py) in `extras/`, that does just this. I think it is reasonably simple. Not as good as documentation, but at least there's an example!

**Comment by glasser** [comment]
Neat. It doesn't connect to my keyboard — maybe the default mac device name is different?

**Comment by algernon** [comment]
Yeah, mac has a different name for it. You should be able to use the same device name you use for flashing (it escapes me what that is under OSX, I'm afraid - if all else fails, the Kaleidoscope makefiles should have a hint or two).

**Comment by glasser** [comment]
Ah, for me it looks like it's `/dev/cu.usbmodemCkbio01` which I found by poking around [https://github.com/keyboardio/Kaleidoscope/blob/8741c68f7b378a8c3efb152b2a828ca0f4a30836/etc/kaleidoscope-builder.conf#L47-L58](kaleidoscope-builder.conf).

**Comment by obra** [comment]
In the glorious future, we should invest some time in either finding
Arduino's port detection magic or writing some of our own. The heuristics I
put in place are...not stellar.

**Comment by obra** [comment]
As an aside, https://github.com/keyboardio/keyboardio-controller-osx was
the pre-Focus little hack I put together to have the host tell the keyboard
what the foreground program was on OS X.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#412.
