### ISSUE TITLE
New protocol and API ideas

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-Focus#8]
Having written tools that interface with Focus, and having used it in my firmware for quite a while, there are a few lessons learned:

- The text-based protocol is nice, but not the easiest to work with on the host side. In particular, it is sometimes not completely clear which response belongs to which request, and where things end.
- The API is not very convenient. Using linked lists was a good idea at the time, but we can do better, more efficient now.
- The protocol itself isn't well specified, I believe.

For these reasons, I propose a few changes, all of them incompatible with previous versions:

The Protocol
==========

We'd still use a text-based protocol, one that is easy for a human to write, if need be. But while we had a `command params\n` as the request format, we'd have `id command params\n` instead. The reply would always start with the same `id`, for easier matching responses. Responses would also be a single line, instead of terminating with a line with only a single dot on it.

This makes the protocol clearer, and communication more straightforward, and would make it easier to allow for device-initiated communication: if the host sees a message that has an id it did not send, then that's coming from the device.

Examples:

```
> r01 help
< r01 help version eeprom.free eeprom.contents
```

```
< k01 KEYDOWN 0 0
< k02 KEYUP 0 0
```

The main changes are the introduction of the id, and mandating one-line responses. Also, we do not interleave responses: they will always be answered in the same order as requests are received. Mind you, device-initiated communication may still interfere.

The API
=======

We're currently using a linked list, which is... a bit of a waste of RAM. Instead, we could use a `Kaleidoscope.use`-like trick to collect all the focus handlers into a dedicated function, which we may call `Focus.handler`. Each handler would get called with the id, and the command as params. If they read from Serial, they will need to signal that, and no other handler will process the request then. Otherwise other handlers will get their turn too.

This means that plugins will be able to respond to `help` and similar requests on their own.

This way we get rid of linked lists, saving RAM, and provide a perhaps nicer API to "register" Focus hooks. The downside is that we'll have to register all hooks in one go, collect them in one function, a'la `macroAction`.

Furthermore, instead of having a typedef for the handler function, we'd use a base class. Perhaps. Not sure about that yet. :)

**Comment by obra** [comment]
>
> We'd still use a text-based protocol, one that is easy for a human to
> write, if need be. But while we had a command params\n as the request
> format, we'd have id command params\n instead. The reply would always
> start with the same id, for easier matching responses.
>

If we simply mandated that the host should not send a command until the
client had responded to the previous command, could we avoid the need for
tagged commands and replies?
IMAP works the way you propose. I've learned to write speak IMAP by hand.
It was...not fun.

> Responses would also be a single line, instead of terminating with a line
> with only a single dot on it.
>
> Do we _need_ this requirement?


> This makes the protocol clearer, and communication more straightforward,
> and would make it easier to allow for device-initiated communication: if
> the host sees a message that has an id it did not send, then that's coming
> from the device.
>
> Could we instead just specify one line prefix that meant "this line is
device-initiated and not a response to a host action"? Say "#" or "*"

I'd love to have the device not have to know about or track command IDs.


> Also, we do not interleave responses: they will always be answered in the
> same order as requests are received.
>
+1

**Comment by algernon** [comment]
> If we simply mandated that the host should not send a command until the client had responded to the previous command, could we avoid the need for tagged commands and replies?

The main driving force behind tagged commands was device-initiated communication... but...

> device-initiated and not a response to a host action? Say "#" or "*"

`*` or `#` both sound good.

> I'd love to have the device not have to know about or track command IDs.

It wouldn't have to. It would just need to remember the current one, since it's only ever going to deal with one command at a time. But I like your idea better.

**Comment by algernon** [comment]
A little bit of update on this: keyboardio/Kaleidoscope#362 implements a new `onFocusEvent` hook, which when combined with the - also new - [Kaleidoscope-FocusSerial](https://github.com/keyboardio/Kaleidoscope-FocusSerial) plugin, will replace this one. It does not change the protocol itself, though.

We'll do that in a separate step, if need be. For now, I'll consider this issue solved once existing plugins are converted to the new system.

**Comment by algernon** [comment]
All keyboardio-controlled plugins have been updated for the new Focus API, so lets close this. We'll keep the protocol as-is, with one change: we'll introduce a helper like `Focus.beginNotice`, which would just print our device-initiated prefix (I'd go with `#`). I'll open an issue on `FocusSerial` about that.
